baseurl = "https://blog.zenithar.org/"

languageCode = "fr-fr"
title = "Zenithar'z Blog"
summerization = "html_firstparagraph"
paginate = 9
theme = "bleak"

SectionPagesMenu = "Main"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  project = "/project/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Il existe moins bien mais c'est plus cher !"
  description = "Dévéloppeur, bloggeur enthousiaste, curieux de toutes nouvelles technologies liées à la sécurité, l'architecture, et le web."
  cover = "/images/cover.jpg"

  # Google analytics
  gravatarHash = "1a2807faf3cca1667ff6f04bf5886eff"
  googleAnalyticsUserID = "UA-8114245-4"
  domainVerification = "fc173d84e3a4de948ed4bda2908afd3e"
  disqus = "zenithar"

  [params.author]
    firstName = "Thibault"
    lastName = "NORMAND"
    gender = "male"
    userName = "zenithar"
    image = "//www.gravatar.com/avatar/1a2807faf3cca1667ff6f04bf5886eff.png"
    website = "http://zenithar.org"
    twitter = "zenithar"
    github = "zenithar"
    facebook = "zenithar"
    linkedin = "zenithar"
    gplus = "thibault.normand"
