baseurl = "https://blog.zenithar.org/"

languageCode = "fr-fr"
title = "Zenithar'z Blog"
paginate = 10
theme = "mynimal"

PygmentsStyle = "paraiso-dark"
PygmentsUseClasses = false
PygmentsCodeFences = true

SectionPagesMenu = "Main"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  project = "/project/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Il existe moins bien mais c'est plus cher !"
  description = "Développeur / Expert en Cyber Sécurité, fou, curieux de toutes nouvelles technologies liées à la cyber-sécurité, l'architecture, et le web."
  cover = "https://blog.zenithar.org/images/cover.jpg"

  # Google analytics
  googleAnalyticsUserID = "UA-8114245-4"
  domainVerification = "fc173d84e3a4de948ed4bda2908afd3e"
  disqus = "zenithar"

  accent = "green"
  showBorder = true
  backgroundColor = "white"
  font = "Raleway" # should match the name on Google Fonts!
  highlight = false
  highlightStyle = "solarized-dark"
  highlightLanguages = ["go"]

  [params.author]
    firstName = "Thibault"
    lastName = "NORMAND"
    gender = "male"
    userName = "zenithar"
    image = "https://blog.zenithar.org/images/avatar.jpg"
    website = "http://zenithar.org"
    twitter = "zenithar"
    github = "zenithar"
    facebook = "zenithar"
    linkedin = "zenithar"
    gplus = "thibault.normand"
    gravatarHash = "1a2807faf3cca1667ff6f04bf5886eff"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.icon]]
    url = "/resume-fr/"
    name = "user-circle-o"
    weight = 1

[[menu.icon]]
    url = "http://www.google.com/recaptcha/mailhide/d?k=01IIc-s5LNYiS-CG_gthn4PA==&c=r5Ctx8RMDz422qmYESfk1g=="
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/Zenithar/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/zenithar/"
    name = "twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/zenithar/"
    name = "linkedin"
    weight = 5
